buildscript {
	repositories {
		google()
		mavenCentral()
		maven {
			name = "r8"
			url = "https://storage.googleapis.com/r8-releases/raw"
			content { includeGroup("com.android.tools") }
		}
	}

	dependencies {
		classpath "com.android.tools:r8:9.0.32"
		classpath "com.android.tools.build:gradle:9.0.0"
	}
}

subprojects {
	repositories {
		google()
		mavenCentral()
	}
}