apply plugin: "com.android.application"
apply from: file("$rootDir/projectСonfig.gradle")

android {
	enableKotlin = false

	namespace = config.applicationId

	compileSdk = config.compileSdkVersion
	buildToolsVersion = config.buildToolsVersion

	androidResources.localeFilters = ["en"]

	defaultConfig {
		applicationId = config.applicationId

		minSdk = config.minSdkVersion
		targetSdk = config.compileSdkVersion

		addManifestPlaceholders(appName: config.appName)

		versionCode = config.versionCode
		versionName = config.versionName
	}

	compileOptions.incremental = true
	lint.abortOnError = false
	packagingOptions.jniLibs.useLegacyPackaging = false

	dependenciesInfo {
		includeInApk = false
		includeInBundle = false
	}

	buildTypes {
		debug {
			debuggable = true
			minifyEnabled = false
			crunchPngs = false
			shrinkResources = false
		}

		release {
			debuggable = false
			minifyEnabled = true
			crunchPngs = true
			shrinkResources = true
			proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "$rootDir/proguardRules.pro")
		}
	}

}

java.toolchain {
	languageVersion = config.javaVersion
	vendor = JvmVendorSpec.ADOPTIUM
}